import { useState, useEffect, useMemo } from 'react';
import Papa from 'papaparse';

/**
 * CSV path (served by Vite from frontend/public/)
 * Sample of real premium university maintenance data (10,000 rows)
 * Generated by sample_csv.py from 760,982 row source CSV.
 */
const CSV_PATH = '/cost_data_sample.csv';

/**
 * Maps a row from the real CSV into the shape the dashboard components expect.
 * Real column names on the left, dashboard-expected names on the right.
 */
const mapRealRow = (row) => {
  const buildingId = String(row.BuildingID);
  const buildingName = (row.BuildingName || '').trim();
  // Use the name if it's there, otherwise fall back to "Building <ID>"
  const buildingLabel = buildingName.length > 0 ? buildingName : `Building ${buildingId}`;

  return {
    WOId: row.WOID,
    WOStartDate: row.WOStartDate,
    SystemDescription: row.SystemDescription,
    SubsystemDescription: row.SubsystemDescription,
    MaintenanceType: row['PPM/UPM'],
    WOPriority: row.WOPriority,
    UniversityID: String(row.UniversityID),
    BuildingID: buildingId,
    BuildingLabel: buildingLabel,        // NEW — name or fallback
    LaborCost: parseFloat(row.LaborCost) || 0,
    MaterialCost: parseFloat(row.MaterialCost) || 0,
    OtherCost: parseFloat(row.OtherCost) || 0,
    TotalCost: parseFloat(row.TotalCost) || 0,
    State: row['State/Province'],
    Country: row.Country
  };
};

/**
 * Fallback mock data generator (kept as safety net if CSV fails to load).
 */
const generateMockCostData = () => {
  const systems = [
    'HVAC', 'Electrical', 'Plumbing', 'Fire Protection', 'Elevators',
    'Roofing', 'Exterior Walls', 'Windows', 'Interior Finishes',
    'Site Improvements', 'Foundation', 'Structural Frame',
    'Security Systems', 'Telecommunications', 'Lighting'
  ];
  const universities = ['University A', 'University B', 'University C'];
  const buildings = ['Building 1', 'Building 2', 'Building 3', 'Building 4', 'Building 5'];
  const priorities = ['Low', 'Medium', 'High', 'Critical'];

  const data = [];
  const endDate = new Date();
  const startDate = new Date();
  startDate.setFullYear(startDate.getFullYear() - 2);
  const numOrders = 500 + Math.floor(Math.random() * 300);

  for (let i = 0; i < numOrders; i++) {
    const system = systems[Math.floor(Math.random() * systems.length)];
    const maintenanceType = Math.random() < 0.35 ? 'PPM' : 'UPM';
    const randomTime = startDate.getTime() + Math.random() * (endDate.getTime() - startDate.getTime());
    const woStartDate = new Date(randomTime);
    let baseLaborCost = 500 + Math.random() * 2000;
    let baseMaterialCost = 200 + Math.random() * 1500;
    let baseOtherCost = 50 + Math.random() * 300;
    if (system === 'HVAC') { baseLaborCost *= 1.5; baseMaterialCost *= 1.3; }
    else if (system === 'Elevators') { baseLaborCost *= 1.8; baseMaterialCost *= 1.5; }
    if (maintenanceType === 'UPM') { baseLaborCost *= 1.4; baseMaterialCost *= 1.2; baseOtherCost *= 1.3; }
    if (Math.random() < 0.05) {
      const multiplier = 3 + Math.random() * 2;
      baseLaborCost *= multiplier; baseMaterialCost *= multiplier; baseOtherCost *= multiplier;
    }
    const laborCost = Math.round(baseLaborCost * 100) / 100;
    const materialCost = Math.round(baseMaterialCost * 100) / 100;
    const otherCost = Math.round(baseOtherCost * 100) / 100;
    const totalCost = Math.round((laborCost + materialCost + otherCost) * 100) / 100;

    data.push({
      WOId: `WO-${String(i + 1).padStart(6, '0')}`,
      WOStartDate: woStartDate.toISOString().split('T')[0],
      SystemDescription: system,
      SubsystemDescription: `${system} Subsystem ${Math.floor(Math.random() * 3) + 1}`,
      MaintenanceType: maintenanceType,
      WOPriority: priorities[Math.floor(Math.random() * priorities.length)],
      UniversityID: universities[Math.floor(Math.random() * universities.length)],
      BuildingID: buildings[Math.floor(Math.random() * buildings.length)],
      LaborCost: laborCost, MaterialCost: materialCost, OtherCost: otherCost, TotalCost: totalCost,
      State: 'CA', Country: 'USA'
    });
  }
  return data;
};

/**
 * Loads the real CSV sample via fetch + Papa Parse.
 * Returns a promise that resolves to an array of dashboard-shaped rows.
 */
const loadRealCostData = async () => {
  const response = await fetch(CSV_PATH);
  if (!response.ok) {
    throw new Error(`Failed to fetch CSV: ${response.status} ${response.statusText}`);
  }
  const csvText = await response.text();

  return new Promise((resolve, reject) => {
    Papa.parse(csvText, {
      header: true,
      skipEmptyLines: true,
      dynamicTyping: false,
      complete: (results) => {
        if (results.errors && results.errors.length > 0) {
          console.warn('CSV parse warnings:', results.errors.slice(0, 3));
        }
        const mapped = results.data.map(mapRealRow).filter(row => row.WOStartDate);
        console.log(`Loaded ${mapped.length} real work orders from CSV sample`);
        resolve(mapped);
      },
      error: (err) => reject(err)
    });
  });
};

/**
 * Custom hook to load and filter cost analysis data.
 * Tries real CSV first, falls back to mock data on failure.
 */
export const useCostAnalysisData = (filters = {}) => {
  const [rawData, setRawData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const loadData = async () => {
      try {
        setLoading(true);
        const data = await loadRealCostData();
        setRawData(data);
        setError(null);
      } catch (err) {
        console.warn('Real CSV failed, falling back to mock data:', err.message);
        setRawData(generateMockCostData());
        setError(null);
      } finally {
        setLoading(false);
      }
    };
    loadData();
  }, []);

  const filteredData = useMemo(() => {
    let filtered = [...rawData];
    if (filters.dateRange) {
      const { start, end } = filters.dateRange;
      filtered = filtered.filter(item => {
        const itemDate = new Date(item.WOStartDate);
        return itemDate >= start && itemDate <= end;
      });
    }
    if (filters.university && filters.university !== 'All') {
      filtered = filtered.filter(item => item.UniversityID === filters.university);
    }
    if (filters.building && filters.building !== 'All') {
      filtered = filtered.filter(item => item.BuildingID === filters.building);
    }
    if (filters.system && filters.system !== '') {
      const searchTerm = filters.system.toLowerCase();
      filtered = filtered.filter(item =>
        item.SystemDescription && item.SystemDescription.toLowerCase().includes(searchTerm)
      );
    }
    if (filters.maintenanceType && filters.maintenanceType !== 'All') {
      filtered = filtered.filter(item => item.MaintenanceType === filters.maintenanceType);
    }
    return filtered;
  }, [rawData, filters]);

  const aggregations = useMemo(() => {
    if (filteredData.length === 0) {
      return {
        totalCost: 0, avgCostPerWO: 0, ppmTotalCost: 0, upmTotalCost: 0,
        mostExpensiveSystem: 'N/A', outlierCount: 0, outlierThreshold: 0
      };
    }
    const totalCost = filteredData.reduce((sum, item) => sum + item.TotalCost, 0);
    const avgCostPerWO = totalCost / filteredData.length;
    const ppmData = filteredData.filter(item => item.MaintenanceType === 'PPM');
    const upmData = filteredData.filter(item => item.MaintenanceType === 'UPM');
    const ppmTotalCost = ppmData.reduce((sum, item) => sum + item.TotalCost, 0);
    const upmTotalCost = upmData.reduce((sum, item) => sum + item.TotalCost, 0);

    const systemCosts = {};
    filteredData.forEach(item => {
      if (!item.SystemDescription) return;
      systemCosts[item.SystemDescription] = (systemCosts[item.SystemDescription] || 0) + item.TotalCost;
    });
    const mostExpensiveSystem = Object.keys(systemCosts).length > 0
      ? Object.keys(systemCosts).reduce((a, b) => systemCosts[a] > systemCosts[b] ? a : b)
      : 'N/A';

    const sortedCosts = filteredData.map(item => item.TotalCost).sort((a, b) => a - b);
    const p95Index = Math.floor(sortedCosts.length * 0.95);
    const outlierThreshold = sortedCosts[p95Index] || 0;
    const outlierCount = filteredData.filter(item => item.TotalCost > outlierThreshold).length;

    return {
      totalCost, avgCostPerWO, ppmTotalCost, upmTotalCost,
      mostExpensiveSystem, outlierCount, outlierThreshold
    };
  }, [filteredData]);

  return { rawData, filteredData, loading, error, aggregations };
};