import { useState, useEffect, useMemo } from 'react';

/**
 * Hook to load real heatmap data from the dashboard CSV files
 * Generated by the ML pipeline (SubsystemDescription + BuildingName)
 */
export const useRiskHeatmapData = (selectedUniversity, selectedBuilding) => {
  const [buildingData, setBuildingData] = useState([]);
  const [universityData, setUniversityData] = useState([]);
  const [metadata, setMetadata] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Load data on mount
  useEffect(() => {
    const loadData = async () => {
      try {
        setLoading(true);
        setError(null);

        // For development: Check if dashboard files exist, otherwise use mock data
        const useMockData = true; // Set to false when backend API is ready

        if (useMockData) {
          // Use mock data for now (real CSV loading requires backend API)
          console.log('Using mock data - real CSV files are in data/dashboard/');

          const mockBuilding = generateMockBuildingData();
          const mockUniversity = generateMockUniversityData();
          const mockMeta = generateMockMetadata();

          console.log('Mock building data:', mockBuilding.length, 'rows');
          console.log('Mock university data:', mockUniversity.length, 'rows');
          console.log('Mock metadata:', mockMeta);
          console.log('Sample building row:', mockBuilding[0]);

          setBuildingData(mockBuilding);
          setUniversityData(mockUniversity);
          setMetadata(mockMeta);
        } else {
          // TODO: Load real data from API endpoints
          // const buildingRes = await fetch('/api/dashboard/building_level_heatmap.csv');
          // const universityRes = await fetch('/api/dashboard/university_level_heatmap.csv');
          // const metaRes = await fetch('/api/dashboard/metadata.json');

          // For now, fall back to mock data
          const mockBuilding = generateMockBuildingData();
          const mockUniversity = generateMockUniversityData();
          const mockMeta = generateMockMetadata();

          setBuildingData(mockBuilding);
          setUniversityData(mockUniversity);
          setMetadata(mockMeta);
        }

        setLoading(false);
      } catch (err) {
        console.error('Error loading heatmap data:', err);
        setError(err.message);
        setLoading(false);
      }
    };

    loadData();
  }, []);

  // Filter data based on selection
  const filteredData = useMemo(() => {
    if (!buildingData.length || !universityData.length) {
      return { mlHeatmap: [], historicalHeatmap: [], metadata: null };
    }

    let data;
    if (selectedBuilding === 'all') {
      // Use university-level aggregation
      data = universityData.filter(row => row.UniversityID === selectedUniversity);
    } else {
      // Use building-level data
      data = buildingData.filter(row =>
        row.UniversityID === selectedUniversity &&
        row.BuildingID === selectedBuilding
      );
    }

    // Format data for Heatmap component (expects SystemDescription, MonthNum, ml_risk)
    const mlHeatmap = data.map(row => ({
      SystemDescription: row.SubsystemDescription,  // Use subsystem as system
      MonthNum: row.MonthNum,
      ml_risk: row.ml_risk,
      BuildingName: row.BuildingName,
      coverage: row.coverage
    }));

    const historicalHeatmap = data.map(row => ({
      SystemDescription: row.SubsystemDescription,
      MonthNum: row.MonthNum,
      hist_asset_rate: row.hist_asset_rate,
      hist_shock_rate: row.hist_shock_rate
    }));

    console.log('Filtered data:', data.length, 'rows');
    console.log('ML Heatmap:', mlHeatmap.length, 'rows');
    if (mlHeatmap.length > 0) {
      console.log('Sample ML row:', mlHeatmap[0]);
    }

    return {
      mlHeatmap,
      historicalHeatmap,
      metadata
    };
  }, [buildingData, universityData, metadata, selectedUniversity, selectedBuilding]);

  return {
    ...filteredData,
    loading,
    error
  };
};

// ========================================
// MOCK DATA GENERATORS (Updated Schema)
// ========================================

const seededRandom = (seed) => {
  let x = Math.sin(seed++) * 10000;
  return x - Math.floor(x);
};

const generateMockBuildingData = () => {
  const data = [];
  let seed = 12345;

  // Using real subsystems from the pipeline
  const subsystems = [
    'Lighting and Branch Wiring',
    'Distribution Systems',
    'Sprinklers',
    'Terminal & Package Units',
    'Plumbing Fixtures',
    'Communications & Security',
    'Interior Doors',
    'Heat Generation Systems',
    'Domestic Water Distribution',
    'Controls and Instrumentation'
  ];

  const universities = [10, 11];
  const buildings = {
    10: [
      { id: '0009', name: 'STUDENT UNION PARKING GARAGE' },
      { id: '0099', name: 'Engineering Hall' },
      { id: '0106', name: 'Science Building' },
      { id: '0113', name: 'Library' },
      { id: '0132', name: 'Student Center' }
    ],
    11: [
      { id: '0001', name: 'Administration Building' },
      { id: '0002', name: 'Research Center' },
      { id: '0003', name: 'Sports Complex' },
      { id: '0004', name: 'Dining Hall' }
    ]
  };

  universities.forEach(uni => {
    buildings[uni].forEach(building => {
      subsystems.forEach(subsystem => {
        for (let month = 1; month <= 12; month++) {
          let baseRisk = 0.15;

          // Seasonal patterns
          if (subsystem.includes('Heat Generation')) {
            baseRisk = [12, 1, 2].includes(month) ? 0.65 : 0.25;
          } else if (subsystem.includes('Terminal & Package')) {
            baseRisk = [6, 7, 8].includes(month) ? 0.55 : 0.30;
          } else if (subsystem.includes('Plumbing') || subsystem.includes('Water')) {
            baseRisk = [12, 1, 2].includes(month) ? 0.45 : 0.25;
          } else {
            baseRisk = 0.15 + seededRandom(seed++) * 0.25;
          }

          data.push({
            UniversityID: uni,
            BuildingID: building.id,
            BuildingName: building.name,
            SubsystemDescription: subsystem,
            MonthNum: month,
            ml_risk: Math.min(0.95, baseRisk + (seededRandom(seed++) - 0.5) * 0.1),
            hist_asset_rate: Math.min(0.5, baseRisk * 0.5 + seededRandom(seed++) * 0.1),
            hist_shock_rate: Math.min(0.3, baseRisk * 0.3 + seededRandom(seed++) * 0.05),
            coverage: Math.floor(50 + seededRandom(seed++) * 200)
          });
        }
      });
    });
  });

  return data;
};

const generateMockUniversityData = () => {
  const data = [];
  let seed = 54321;

  const subsystems = [
    'Lighting and Branch Wiring',
    'Distribution Systems',
    'Sprinklers',
    'Terminal & Package Units',
    'Plumbing Fixtures',
    'Communications & Security',
    'Interior Doors',
    'Heat Generation Systems',
    'Domestic Water Distribution',
    'Controls and Instrumentation',
    'Commercial Equipment',
    'Ceiling Finishes',
    'Electrical Service & Distribution',
    'Exterior Doors'
  ];

  const universities = [10, 11];

  universities.forEach(uni => {
    subsystems.forEach(subsystem => {
      for (let month = 1; month <= 12; month++) {
        let baseRisk = 0.15;

        if (subsystem.includes('Heat Generation')) {
          baseRisk = [12, 1, 2].includes(month) ? 0.60 : 0.22;
        } else if (subsystem.includes('Terminal & Package')) {
          baseRisk = [6, 7, 8].includes(month) ? 0.50 : 0.28;
        } else if (subsystem.includes('Plumbing') || subsystem.includes('Water')) {
          baseRisk = [12, 1, 2].includes(month) ? 0.40 : 0.22;
        } else {
          baseRisk = 0.15 + seededRandom(seed++) * 0.20;
        }

        data.push({
          UniversityID: uni,
          SubsystemDescription: subsystem,
          MonthNum: month,
          ml_risk: Math.min(0.95, baseRisk + (seededRandom(seed++) - 0.5) * 0.08),
          hist_asset_rate: Math.min(0.5, baseRisk * 0.45 + seededRandom(seed++) * 0.08),
          hist_shock_rate: Math.min(0.3, baseRisk * 0.25 + seededRandom(seed++) * 0.04),
          coverage: Math.floor(100 + seededRandom(seed++) * 400)
        });
      }
    });
  });

  return data;
};

const generateMockMetadata = () => {
  return {
    universities: [10, 11],
    buildings_by_university: {
      10: ['0009', '0099', '0106', '0113', '0132'],
      11: ['0001', '0002', '0003', '0004']
    },
    building_names: {
      '0009': 'STUDENT UNION PARKING GARAGE',
      '0099': 'Engineering Hall',
      '0106': 'Science Building',
      '0113': 'Library',
      '0132': 'Student Center',
      '0001': 'Administration Building',
      '0002': 'Research Center',
      '0003': 'Sports Complex',
      '0004': 'Dining Hall'
    }
  };
};
