import { useState, useEffect, useMemo } from 'react';

/**
 * Hook to load real heatmap data from the dashboard CSV files
 * Generated by the ML pipeline (SubsystemDescription + BuildingName)
 */
export const useRiskHeatmapData = (selectedUniversity, selectedBuilding) => {
  const [buildingData, setBuildingData] = useState([]);
  const [universityData, setUniversityData] = useState([]);
  const [metadata, setMetadata] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  // Load data on mount
  useEffect(() => {
    const loadData = async () => {
      try {
        setLoading(true);
        setError(null);

        // For development: Check if dashboard files exist, otherwise use mock data
        const useMockData = true; // Set to false when backend API is ready

        if (useMockData) {
          // Use mock data for now (real CSV loading requires backend API)
          console.log('Using mock data - real CSV files are in data/dashboard/');

          const mockBuilding = generateMockBuildingData();
          const mockUniversity = generateMockUniversityData();
          const mockMeta = generateMockMetadata();

          console.log('Mock building data:', mockBuilding.length, 'rows');
          console.log('Mock university data:', mockUniversity.length, 'rows');
          console.log('Mock metadata:', mockMeta);
          console.log('Sample building row:', mockBuilding[0]);

          setBuildingData(mockBuilding);
          setUniversityData(mockUniversity);
          setMetadata(mockMeta);
        } else {
          // TODO: Load real data from API endpoints
          // const buildingRes = await fetch('/api/dashboard/building_level_heatmap.csv');
          // const universityRes = await fetch('/api/dashboard/university_level_heatmap.csv');
          // const metaRes = await fetch('/api/dashboard/metadata.json');

          // For now, fall back to mock data
          const mockBuilding = generateMockBuildingData();
          const mockUniversity = generateMockUniversityData();
          const mockMeta = generateMockMetadata();

          setBuildingData(mockBuilding);
          setUniversityData(mockUniversity);
          setMetadata(mockMeta);
        }

        setLoading(false);
      } catch (err) {
        console.error('Error loading heatmap data:', err);
        setError(err.message);
        setLoading(false);
      }
    };

    loadData();
  }, []);

  // Filter data based on selection
  const filteredData = useMemo(() => {
    if (!buildingData.length || !universityData.length) {
      return { mlHeatmap: [], historicalHeatmap: [], metadata: null, subsystemData: [] };
    }

    let data;
    if (selectedBuilding === 'all') {
      // Use university-level aggregation
      data = universityData.filter(row => row.UniversityID === selectedUniversity);
    } else {
      // Use building-level data
      data = buildingData.filter(row =>
        row.UniversityID === selectedUniversity &&
        row.BuildingID === selectedBuilding
      );
    }

    // Keep subsystem-level data for drill-down
    const subsystemData = data.map(row => ({
      SystemDescription: row.SystemDescription,
      SubsystemDescription: row.SubsystemDescription,
      MonthNum: row.MonthNum,
      ml_risk: row.ml_risk,
      hist_asset_rate: row.hist_asset_rate,
      hist_shock_rate: row.hist_shock_rate,
      BuildingName: row.BuildingName,
      coverage: row.coverage
    }));

    // Aggregate subsystems to system level for main heatmap
    const systemAggregation = {};
    data.forEach(row => {
      const key = `${row.SystemDescription}_${row.MonthNum}`;
      if (!systemAggregation[key]) {
        systemAggregation[key] = {
          SystemDescription: row.SystemDescription,
          MonthNum: row.MonthNum,
          ml_risk_sum: 0,
          ml_risk_count: 0,
          hist_asset_sum: 0,
          hist_shock_sum: 0,
          coverage_sum: 0
        };
      }
      systemAggregation[key].ml_risk_sum += row.ml_risk || 0;
      systemAggregation[key].ml_risk_count += 1;
      systemAggregation[key].hist_asset_sum += row.hist_asset_rate || 0;
      systemAggregation[key].hist_shock_sum += row.hist_shock_rate || 0;
      systemAggregation[key].coverage_sum += row.coverage || 0;
    });

    // Format system-level data for main Heatmap component
    const mlHeatmap = Object.values(systemAggregation).map(agg => ({
      SystemDescription: agg.SystemDescription,
      MonthNum: agg.MonthNum,
      ml_risk: agg.ml_risk_sum / agg.ml_risk_count,
      coverage: agg.coverage_sum
    }));

    const historicalHeatmap = Object.values(systemAggregation).map(agg => ({
      SystemDescription: agg.SystemDescription,
      MonthNum: agg.MonthNum,
      hist_asset_rate: agg.hist_asset_sum / agg.ml_risk_count,
      hist_shock_rate: agg.hist_shock_sum / agg.ml_risk_count
    }));

    console.log('Filtered data:', data.length, 'rows');
    console.log('System-level Heatmap:', mlHeatmap.length, 'rows');
    console.log('Subsystem-level data:', subsystemData.length, 'rows');
    if (mlHeatmap.length > 0) {
      console.log('Sample system row:', mlHeatmap[0]);
    }

    return {
      mlHeatmap,
      historicalHeatmap,
      subsystemData,  // New: subsystem-level data for drill-down
      metadata
    };
  }, [buildingData, universityData, metadata, selectedUniversity, selectedBuilding]);

  return {
    ...filteredData,
    loading,
    error
  };
};

// ========================================
// MOCK DATA GENERATORS (Updated Schema)
// ========================================

const seededRandom = (seed) => {
  let x = Math.sin(seed++) * 10000;
  return x - Math.floor(x);
};

const generateMockBuildingData = () => {
  const data = [];
  let seed = 12345;

  // System-to-Subsystem mapping (from FMUCD.csv schema)
  const subsystemToSystem = {
    'Lighting and Branch Wiring': 'Electrical',
    'Communications & Security': 'Electrical',
    'Electrical Service & Distribution': 'Electrical',
    'Distribution Systems': 'HVAC',
    'Terminal & Package Units': 'HVAC',
    'Heat Generation Systems': 'HVAC',
    'Controls and Instrumentation': 'HVAC',
    'Cooling Generation Systems': 'HVAC',
    'Sprinklers': 'Fire Protection',
    'Standpipes': 'Fire Protection',
    'Plumbing Fixtures': 'Plumbing',
    'Domestic Water Distribution': 'Plumbing',
    'Sanitary Waste': 'Plumbing',
    'Rain Water Drainage': 'Plumbing',
    'Interior Doors': 'Interior Construction',
    'Interior Windows': 'Interior Construction',
    'Wall Finishes': 'Interior Finishes',
    'Floor Finishes': 'Interior Finishes',
    'Ceiling Finishes': 'Interior Finishes',
    'Commercial Equipment': 'Equipment'
  };

  // Using real subsystems from the pipeline
  const subsystems = [
    'Lighting and Branch Wiring',
    'Electrical Service & Distribution',
    'Communications & Security',
    'Distribution Systems',
    'Terminal & Package Units',
    'Heat Generation Systems',
    'Controls and Instrumentation',
    'Sprinklers',
    'Plumbing Fixtures',
    'Domestic Water Distribution',
    'Interior Doors',
    'Wall Finishes',
    'Ceiling Finishes'
  ];

  const universities = [10, 11];
  const buildings = {
    10: [
      { id: '0009', name: 'STUDENT UNION PARKING GARAGE' },
      { id: '0099', name: 'Engineering Hall' },
      { id: '0106', name: 'Science Building' },
      { id: '0113', name: 'Library' },
      { id: '0132', name: 'Student Center' }
    ],
    11: [
      { id: '0001', name: 'Administration Building' },
      { id: '0002', name: 'Research Center' },
      { id: '0003', name: 'Sports Complex' },
      { id: '0004', name: 'Dining Hall' }
    ]
  };

  universities.forEach(uni => {
    buildings[uni].forEach(building => {
      subsystems.forEach(subsystem => {
        for (let month = 1; month <= 12; month++) {
          let baseRisk = 0.15;

          // Seasonal patterns
          if (subsystem.includes('Heat Generation')) {
            baseRisk = [12, 1, 2].includes(month) ? 0.65 : 0.25;
          } else if (subsystem.includes('Terminal & Package')) {
            baseRisk = [6, 7, 8].includes(month) ? 0.55 : 0.30;
          } else if (subsystem.includes('Plumbing') || subsystem.includes('Water')) {
            baseRisk = [12, 1, 2].includes(month) ? 0.45 : 0.25;
          } else {
            baseRisk = 0.15 + seededRandom(seed++) * 0.25;
          }

          data.push({
            UniversityID: uni,
            BuildingID: building.id,
            BuildingName: building.name,
            SystemDescription: subsystemToSystem[subsystem] || 'Other',
            SubsystemDescription: subsystem,
            MonthNum: month,
            ml_risk: Math.min(0.95, baseRisk + (seededRandom(seed++) - 0.5) * 0.1),
            hist_asset_rate: Math.min(0.5, baseRisk * 0.5 + seededRandom(seed++) * 0.1),
            hist_shock_rate: Math.min(0.3, baseRisk * 0.3 + seededRandom(seed++) * 0.05),
            coverage: Math.floor(50 + seededRandom(seed++) * 200)
          });
        }
      });
    });
  });

  return data;
};

const generateMockUniversityData = () => {
  const data = [];
  let seed = 54321;

  // System-to-Subsystem mapping (same as building level)
  const subsystemToSystem = {
    'Lighting and Branch Wiring': 'Electrical',
    'Communications & Security': 'Electrical',
    'Electrical Service & Distribution': 'Electrical',
    'Distribution Systems': 'HVAC',
    'Terminal & Package Units': 'HVAC',
    'Heat Generation Systems': 'HVAC',
    'Controls and Instrumentation': 'HVAC',
    'Cooling Generation Systems': 'HVAC',
    'Sprinklers': 'Fire Protection',
    'Standpipes': 'Fire Protection',
    'Plumbing Fixtures': 'Plumbing',
    'Domestic Water Distribution': 'Plumbing',
    'Sanitary Waste': 'Plumbing',
    'Rain Water Drainage': 'Plumbing',
    'Interior Doors': 'Interior Construction',
    'Interior Windows': 'Interior Construction',
    'Wall Finishes': 'Interior Finishes',
    'Floor Finishes': 'Interior Finishes',
    'Ceiling Finishes': 'Interior Finishes',
    'Commercial Equipment': 'Equipment',
    'Exterior Doors': 'Exterior Enclosure'
  };

  const subsystems = [
    'Lighting and Branch Wiring',
    'Electrical Service & Distribution',
    'Communications & Security',
    'Distribution Systems',
    'Terminal & Package Units',
    'Heat Generation Systems',
    'Controls and Instrumentation',
    'Sprinklers',
    'Plumbing Fixtures',
    'Domestic Water Distribution',
    'Interior Doors',
    'Commercial Equipment',
    'Ceiling Finishes',
    'Exterior Doors'
  ];

  const universities = [10, 11];

  universities.forEach(uni => {
    subsystems.forEach(subsystem => {
      for (let month = 1; month <= 12; month++) {
        let baseRisk = 0.15;

        if (subsystem.includes('Heat Generation')) {
          baseRisk = [12, 1, 2].includes(month) ? 0.60 : 0.22;
        } else if (subsystem.includes('Terminal & Package')) {
          baseRisk = [6, 7, 8].includes(month) ? 0.50 : 0.28;
        } else if (subsystem.includes('Plumbing') || subsystem.includes('Water')) {
          baseRisk = [12, 1, 2].includes(month) ? 0.40 : 0.22;
        } else {
          baseRisk = 0.15 + seededRandom(seed++) * 0.20;
        }

        data.push({
          UniversityID: uni,
          SystemDescription: subsystemToSystem[subsystem] || 'Other',
          SubsystemDescription: subsystem,
          MonthNum: month,
          ml_risk: Math.min(0.95, baseRisk + (seededRandom(seed++) - 0.5) * 0.08),
          hist_asset_rate: Math.min(0.5, baseRisk * 0.45 + seededRandom(seed++) * 0.08),
          hist_shock_rate: Math.min(0.3, baseRisk * 0.25 + seededRandom(seed++) * 0.04),
          coverage: Math.floor(100 + seededRandom(seed++) * 400)
        });
      }
    });
  });

  return data;
};

const generateMockMetadata = () => {
  return {
    universities: [10, 11],
    buildings_by_university: {
      10: ['0009', '0099', '0106', '0113', '0132'],
      11: ['0001', '0002', '0003', '0004']
    },
    building_names: {
      '0009': 'STUDENT UNION PARKING GARAGE',
      '0099': 'Engineering Hall',
      '0106': 'Science Building',
      '0113': 'Library',
      '0132': 'Student Center',
      '0001': 'Administration Building',
      '0002': 'Research Center',
      '0003': 'Sports Complex',
      '0004': 'Dining Hall'
    }
  };
};
